FROM node:17-alpine
RUN mkdir /home/frontend && chown node:node /home/frontend
WORKDIR /home/frontend
USER node
COPY --chown=node:node package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY --chown=node:node . .
EXPOSE 3000
CMD ["yarn", "start"]