# STAGE 1
FROM node:17-alpine as builder
WORKDIR /frontend
COPY package.json .
COPY yarn.lock .
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# STAGE 2
FROM nginx:1.23-alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off"]